In [1]:
#Test
import pandas as pd
data = pd.read_csv('airbnb_test.csv', parse_dates=['host_since'])

data = data.drop(columns=['listing_url', 'scrape_id', 'last_scraped', 'name_x', 'summary', 'space', 'description', 'neighborhood_overview'])
data = data.drop(columns=['notes', 'transit', 'access', 'interaction', 'house_rules', 'thumbnail_url', 'medium_url', 'picture_url',])
data = data.drop(columns=['xl_picture_url', 'host_id_x', 'host_url', 'host_name_x', 'host_acceptance_rate', 'host_thumbnail_url', 'host_picture_url'])
data = data.drop(columns=['host_about', 'host_listings_count', 'country', 'calendar_last_scraped', 'requires_license', 'license'])
data = data.drop(columns=['jurisdiction_names', 'host_id_y', 'host_name_y', 'host_location', 'street', 'city', 'state', 'country_code'])
data = data.drop(columns=['smart_location', 'square_feet', 'name_y', 'latitude_y', 'longitude_y', 'room_type_y', 'experiences_offered'])
data = data.drop(columns=['calendar_updated', 'first_review', 'last_review_y'])
data = data.drop(columns=['market', 'require_guest_profile_picture', 'reviews_per_month_y', 'calculated_host_listings_count_y'])
data = data.drop(columns=['availability_365_y', 'host_verifications', 'date'])
# Location data
data = data.drop(columns=['host_neighbourhood', 'neighbourhood_x', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'zipcode', 'neighbourhood_y', 'neighbourhood_group'])
# data = data.drop(columns=['latitude_x', 'longitude_x', 'is_location_exact'])
# availability data
data = data.drop(columns=['availability_365_x', 'availability_30', 'availability_60', 'available', 'has_availability'])
# response data
data = data.drop(columns=['host_response_time', 'host_response_rate'])
# review data
data = data.drop(columns=['last_review_x'])


data['cancellation_policy_mapped'] = data.cancellation_policy.map({'super_strict_60': 0, 'strict_14_with_grace_period':1, 'moderate':2, 'flexible':3})
data = data.drop(columns=['cancellation_policy'])
data['bed_code'] = data.bed_type.map({'Real Bed':2, 'Pull-out Sofa':1, 'Futon':0})
data = data.drop(columns=['bed_type'])
data['room_code'] = data.room_type_x.map({'Entire home/apt':1, 'Private room':0, 'Shared room':2})
data = data.drop(columns=['room_type_x'])
data['verified_id'] = data.host_identity_verified.map({'t':1, 'f':0})
data = data.drop(columns=['host_identity_verified'])
data['profile_pic'] = data.host_has_profile_pic.map({'t':1, 'f':0})
data = data.drop(columns=['host_has_profile_pic'])
data['superhost'] = data.host_is_superhost.map({'t':1, 'f':0})
data = data.drop(columns=['host_is_superhost'])
data['phone_verified'] = data.require_guest_phone_verification.map({'t':1, 'f':0})
data = data.drop(columns=['require_guest_phone_verification'])
data['buisiness_travel'] = data.is_business_travel_ready.map({'t':1, 'f':0})
data = data.drop(columns=['is_business_travel_ready'])
data['instant_book'] = data.instant_bookable.map({'t':1, 'f':0})
data = data.drop(columns=['instant_bookable'])

test_data = data
data.to_csv('airbnb_test_coded.csv')

In [2]:
# Training
import pandas as pd
data = pd.read_csv('airbnb_merged.csv')

data = data.drop(columns=['listing_url', 'scrape_id', 'last_scraped', 'name_x', 'summary', 'space', 'description', 'neighborhood_overview'])
data = data.drop(columns=['notes', 'transit', 'access', 'interaction', 'house_rules', 'thumbnail_url', 'medium_url', 'picture_url',])
data = data.drop(columns=['xl_picture_url', 'host_id_x', 'host_url', 'host_name_x', 'host_acceptance_rate', 'host_thumbnail_url', 'host_picture_url'])
data = data.drop(columns=['host_about', 'host_listings_count', 'country', 'calendar_last_scraped', 'requires_license', 'license'])
data = data.drop(columns=['jurisdiction_names', 'host_id_y', 'host_name_y', 'host_location', 'street', 'city', 'state', 'country_code'])
data = data.drop(columns=['smart_location', 'square_feet', 'name_y', 'latitude_y', 'longitude_y', 'room_type_y', 'price_y', 'experiences_offered'])
data = data.drop(columns=['weekly_price', 'monthly_price', 'calendar_updated', 'first_review', 'last_review_y'])
data = data.drop(columns=['market', 'require_guest_profile_picture', 'reviews_per_month_y', 'calculated_host_listings_count_y'])
data = data.drop(columns=['availability_365_y', 'host_verifications', 'date'])
# Location data
data = data.drop(columns=['host_neighbourhood', 'neighbourhood_x', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'zipcode', 'neighbourhood_y', 'neighbourhood_group'])
# data = data.drop(columns=['latitude_x', 'longitude_x', 'is_location_exact'])
# availability data
data = data.drop(columns=['availability_365_x', 'availability_30', 'availability_60', 'available', 'has_availability'])
# response data
data = data.drop(columns=['host_response_time', 'host_response_rate'])
# review data
data = data.drop(columns=['last_review_x'])

data.to_csv('airbnb_cleaned.csv')

data['cancellation_policy_mapped'] = data.cancellation_policy.map({'super_strict_60': 0, 'strict_14_with_grace_period':1, 'moderate':2, 'flexible':3})
data = data.drop(columns=['cancellation_policy'])
data['bed_code'] = data.bed_type.map({'Real Bed':2, 'Pull-out Sofa':1, 'Futon':0})
data = data.drop(columns=['bed_type'])
data['room_code'] = data.room_type_x.map({'Entire home/apt':1, 'Private room':0, 'Shared room':2})
data = data.drop(columns=['room_type_x'])
data['verified_id'] = data.host_identity_verified.map({'t':1, 'f':0})
data = data.drop(columns=['host_identity_verified'])
data['profile_pic'] = data.host_has_profile_pic.map({'t':1, 'f':0})
data = data.drop(columns=['host_has_profile_pic'])
data['superhost'] = data.host_is_superhost.map({'t':1, 'f':0})
data = data.drop(columns=['host_is_superhost'])
data['phone_verified'] = data.require_guest_phone_verification.map({'t':1, 'f':0})
data = data.drop(columns=['require_guest_phone_verification'])
data['buisiness_travel'] = data.is_business_travel_ready.map({'t':1, 'f':0})
data = data.drop(columns=['is_business_travel_ready'])
data['instant_book'] = data.instant_bookable.map({'t':1, 'f':0})
data = data.drop(columns=['instant_bookable'])

data.to_csv('airbnb_coded.csv')

/home/pouya/anaconda3/envs/python38/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3062: DtypeWarning: Columns (2,15,16,18,27,33,43,53,54,65,67,68,72,74,76,79,83,88) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [3]:
#Training
import pandas as pd
import seaborn as sns
import sklearn.cluster as cluster
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler as sc
import hdbscan

big_data = pd.read_csv('airbnb_coded.csv')
sc = sc()
pd.options.mode.chained_assignment = None  # default='warn'

# data['property_types'] = data.property_type.map({'Apartment':0, 'House':1, 'Loft':2, 'Hotel':3, 'Condominium':4, 'Tiny house':5, 'Serviced apartment':6, 'Boutique hotel':7,
#                                            'Guest suit':8, 'Houseboat':9, 'Hostel':10, 'Villa':11, 'Townhouse':12, 'Cabin':13, 'Camper/RV':14})
# data['property_types'] = data.property_type.map({'Apartment':0, 'House':1, 'Loft':2, 'Hotel':3, 'Condominium':4, 'Tiny house':5, 'Serviced apartment':6, 'Boutique hotel':7,
#                                            'Guest suit':8, 'Houseboat':9, 'Hostel':10, 'Villa':11, 'Townhouse':12, 'Cabin':13, 'Camper/RV':14})
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
var = 'bathrooms'
var2 = 'accommodates'
var3 = 'cleaning_fee'
var10 = 'price_x'

data = big_data[['property_type', var, var2, var3, var10]]#, 'cleaning_fee', 'security_deposit']]
# data['cleaning_fee'] = data['cleaning_fee'].fillna(data['cleaning_fee'].median())


data[var3] = data[var3].str.replace(',', '')
data[var3] = data[var3].str.replace('$', '')

big_data[var3] = big_data[var3].str.replace(',', '')
big_data[var3] = big_data[var3].str.replace('$', '')

data[var10] = data[var10].str.replace(',', '')
data[var10] = data[var10].str.replace('$', '')

big_data[var10] = big_data[var10].str.replace(',', '')
big_data[var10] = big_data[var10].str.replace('$', '')


data[var][6722] = 0
data[var][4476] = 0
data[var2][6722] = 0
data[var2][4476] = 0
data[var3][6722] = 0
data[var3][4476] = 0
# data['security_deposit'][4476] = 0
# data['security_deposit'] = data['security_deposit'].fillna(data['security_deposit'].median())
data[var] = data[var].fillna(data[var].median())
data[var2] = data[var2].fillna(data[var2].median())
data[var3] = data[var3].fillna(data[var3].median())
data[var10] = data[var10].fillna(data[var10].median())
data['property_type'] = data['property_type'].fillna('Apartment')
# data.head()
data = data.drop(data.index[14973])
big_data = big_data.drop(data.index[14973])
big_data = big_data.drop(big_data.index[6722])
big_data = big_data.drop(big_data.index[4476])
data = data.drop(data.index[6722])
data = data.drop(data.index[4476])
X = data.iloc[:, 1:-1].values
# X = ct.fit_transform(X)
# X = X.todense()
# X = np.array(X)
# X1 = data[var2].values #, data['cleaning_fee'].values, data['security_deposit'].values
# # X2 = 
# y = data['property_type'].values
# cluster_data = []
# for i in range(len(X1)):
#     cluster_data.append([y[i], X1[i]])
# cluster_data = np.array(cluster_data)
# # cluster_data = sc.fit_transform(cluster_data)
# print(len(cluster_data))

clusterer = cluster.KMeans(n_clusters=4)
X = clusterer.fit_predict(X)
# clusterer.fit(X)
# Clusters = clusterer.predict(X)
data['listing_class'] = X
big_data['listing_class'] = X


data = data[['property_type', var, var2, var3, 'listing_class', var10]]
X = data.iloc[:, 1:-2].values
y = data.iloc[:, -2].values
# X = ct.fit_transform(X)
# X = X.todense()
# X = np.array(X)


from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=500, min_samples_leaf=1)
classifier = classifier.fit(X, y)

/home/pouya/anaconda3/envs/python38/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3062: DtypeWarning: Columns (3,8,9,16,18,19,21,22,26) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [4]:
#Test
import pandas as pd
import seaborn as sns
import sklearn.cluster as cluster
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler as sc
import hdbscan

# test_data = pd.read_csv('airbnb_test_coded.csv', parse_dates=['host_since'])
sc = sc()
pd.options.mode.chained_assignment = None  # default='warn'

# data['property_types'] = data.property_type.map({'Apartment':0, 'House':1, 'Loft':2, 'Hotel':3, 'Condominium':4, 'Tiny house':5, 'Serviced apartment':6, 'Boutique hotel':7,
#                                            'Guest suit':8, 'Houseboat':9, 'Hostel':10, 'Villa':11, 'Townhouse':12, 'Cabin':13, 'Camper/RV':14})
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
var = 'bathrooms'
var2 = 'accommodates'
var3 = 'cleaning_fee'





data = test_data[['property_type', var, var2, var3]]


data[var3] = data[var3].str.replace(',', '')
data[var3] = data[var3].str.replace('$', '')

test_data[var3] = test_data[var3].str.replace(',', '')
test_data[var3] = test_data[var3].str.replace('$', '')

test_data['host_since'] = test_data['host_since'].str.replace('DE', '2014-04-16')
# test_data['host_since'] = test_data['host_since'].str.replace('', '2014-04-16')


data[var][3105] = 0
data[var][4476] = 0
data[var2][3105] = 0
data[var2][4476] = 0
data[var3][3105] = 0
data[var3][4476] = 0


data[var] = data[var].fillna(data[var].median())
data[var2] = data[var2].fillna(data[var2].median())
data[var3] = data[var3].fillna(data[var3].median())
data['property_type'] = data['property_type'].fillna('Apartment')

X = data.iloc[:, 1:].values
# X = ct.fit_transform(X)
# X = X.todense()
# X = np.array(X)



data = data[['property_type', var, var2, var3]]
X = data.iloc[:, 1:].values
# X = ct.fit_transform(X)
# X = X.todense()
# X = np.array(X)

y_pred = classifier.predict(X)

data['listing_class'] = y_pred
test_data['listing_class'] = y_pred

big_data.to_csv('airbnb_coded.2.0.csv')
test_data.to_csv('airbnb_test_coded.csv')
print("done")

done


In [5]:
#Training
import pandas as pd
import seaborn as sns
import sklearn.cluster as cluster
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler as sc
import hdbscan

big_data = pd.read_csv('airbnb_coded.2.0.csv', parse_dates=['host_since'])
sc = sc()
pd.options.mode.chained_assignment = None  # default='warn'
plot_kwds = {'alpha' : 0.25, 's' : 80, 'linewidths':0}


from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
var = 'bathrooms'
var2 = 'accommodates'
var3 = 'cleaning_fee'
var4 = 'bedrooms'
var5 = 'beds'
var6 = 'minimum_nights_x'
var7 = 'maximum_nights'
var8 = 'number_of_reviews_y'
var9 = 'listing_class'
var10 = 'price_x'
var11 = 'bed_code'
var12 = 'cancellation_policy_mapped'
var13 = 'room_code'
var14 = 'superhost'
var15 = 'instant_book'
var16 = 'review_scores_location'
var17 = 'review_scores_rating'
var18 = 'host_total_listings_count'
var19 = 'availability_90'
var20 = 'room_code'
var21 = 'extra_people'
var22 = 'property_type'
var23 = 'review_scores_value'
var24 = 'review_scores_cleanliness'
var25 = 'review_scores_checkin'
var26 = 'review_scores_communication'
var27 = 'review_scores_value'
var28 = 'guests_included'
var29 = 'security_deposit'
var30 = 'host_since'
var31 = 'longitude_x'
var32 = 'latitude_x'
var33 = 'amenities'

# big_data = big_data[big_data.price_x < 500]

data = big_data[[var, var2, var3, var4, var5, var6, var7, var8, var11, var12, var13, var14, var15, var16, var17, var18, var19, var20, var21, var22, var23, var24,
                 var25, var26, var27, var28, var29, var30, var31, var32, var33, var9, var10]]



data[var21] = data[var21].str.replace(',', '')
data[var21] = data[var21].str.replace('$', '')

big_data[var21] = big_data[var21].str.replace(',', '')
big_data[var21] = big_data[var21].str.replace('$', '')

data[var29] = data[var29].str.replace(',', '')
data[var29] = data[var29].str.replace('$', '')

big_data[var29] = big_data[var29].str.replace(',', '')
big_data[var29] = big_data[var29].str.replace('$', '')


data[var30] = (big_data.host_since - big_data.host_since.min())
data[var30] = data[var30].values.astype('timedelta64[D]').astype('float')

big_data[var30] = (big_data.host_since - big_data.host_since.min())
big_data[var30] = big_data[var30].values.astype('timedelta64[D]').astype('float')


data[var] = data[var].fillna(data[var].median())
data[var2] = data[var2].fillna(data[var2].median())
data[var3] = data[var3].fillna(data[var3].median())
data[var4] = data[var4].fillna(data[var4].median())
data[var5] = data[var5].fillna(data[var5].median())

data[var6][17990] = data[var6].median()
data[var6][6215] = data[var6].median()
data[var6][11299] = data[var6].median()
data[var6][12737] = data[var6].median()
data[var6][14598] = data[var6].median()
# data[var7][872] = 8000
# data[var7][2372] = 8000
# data[var7][4391] = 8000
# data[var7][17952] = 8000
# data[var7][17990] = data[var7].median()
# data[var7][6351] = data[var7].median()
# data[var7][8341] = data[var7].median()


data[var6] = data[var6].fillna(data[var6].median())
data[var7] = data[var7].fillna(data[var7].median())
data[var8] = data[var8].fillna(data[var8].median())
data[var10] = data[var10].fillna(data[var10].median())
data[var11] = data[var11].fillna(data[var11].median())
data[var12] = data[var12].fillna(data[var12].median())
data[var13] = data[var13].fillna(data[var13].median())
data[var14] = data[var14].fillna(data[var14].median())
data[var15] = data[var15].fillna(data[var15].median())
data[var16] = data[var16].fillna(data[var16].median())
data[var17] = data[var17].fillna(data[var17].median())
data[var18] = data[var18].fillna(data[var18].median())
data[var19] = data[var19].fillna(data[var19].median())
data[var20] = data[var20].fillna(data[var20].median())
data[var21] = data[var21].fillna(data[var21].median())
data[var22] = data[var22].fillna('Apartment')
data[var23] = data[var23].fillna(data[var23].median())
data[var24] = data[var24].fillna(data[var24].median())
data[var25] = data[var25].fillna(data[var25].median())
data[var26] = data[var26].fillna(data[var26].median())
data[var27] = data[var27].fillna(data[var27].median())
data[var28] = data[var28].fillna(data[var28].median())
data[var29] = data[var29].fillna(data[var29].median())
data[var30] = data[var30].fillna(data[var30].median())
data[var31] = data[var31].fillna(data[var31].median())
data[var32] = data[var32].fillna(data[var32].median())






# data[var6][17990] = data[var6].median()

# data = data.drop(data.index[17990])
# data = data.drop(data.index[14598])

data = data[[var31, var32, var10]]

X = data.iloc[:, :-1].values
# y = data.iloc[:, -1].values
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-4])], remainder='passthrough')
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-5])], remainder='passthrough')
# X = ct.fit_transform(X)
# X = X.todense()
# X = np.array(X)
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-6])], remainder='passthrough')
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)

# plt.scatter(data[var6].values, data[var7].values, s=100, c='red', alpha=0.5)
# plt.show()

print(X)
# X[:,-8:] = sc.fit_transform(X[:,-8:])
# X = sc.fit_transform(X)
# print(X[0])
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

# data.head()


# label = hdbscan.HDBSCAN(min_cluster_size=450, min_samples=15).fit_predict(cluster_data)
clusterer = cluster.KMeans(n_clusters=4)
X = clusterer.fit_predict(X)
# clusterer.fit(X)
# Clusters = clusterer.predict(X)
data['loc_class'] = X
big_data['loc_class'] = X
print("clustered")

data = data[[var31, var32, 'loc_class', var10]]
X = data.iloc[:, :-2].values
y = data.iloc[:, -2].values


from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=500, min_samples_leaf=1)
classifier = classifier.fit(X, y)
print("done")

[[13.4462961  52.48141516]
 [13.41708604 52.60610923]
 [13.50276362 52.44614449]
 ...
 [13.29098912 52.4976456 ]
 [13.38508885 52.46504928]
 [13.58954646 52.46768108]]
clustered
done


In [6]:
#Test
import pandas as pd
import seaborn as sns
import sklearn.cluster as cluster
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler as sc
import hdbscan

test_data = pd.read_csv('airbnb_test_coded.csv', parse_dates=['host_since'])
sc = sc()
pd.options.mode.chained_assignment = None  # default='warn'
plot_kwds = {'alpha' : 0.25, 's' : 80, 'linewidths':0}


from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
var = 'bathrooms'
var2 = 'accommodates'
var3 = 'cleaning_fee'
var4 = 'bedrooms'
var5 = 'beds'
var6 = 'minimum_nights_x'
var7 = 'maximum_nights'
var8 = 'number_of_reviews_y'
var11 = 'bed_code'
var12 = 'cancellation_policy_mapped'
var13 = 'room_code'
var14 = 'superhost'
var15 = 'instant_book'
var16 = 'review_scores_location'
var17 = 'review_scores_rating'
var18 = 'host_total_listings_count'
var19 = 'availability_90'
var20 = 'room_code'
var21 = 'extra_people'
var22 = 'property_type'
var23 = 'review_scores_value'
var24 = 'review_scores_cleanliness'
var25 = 'review_scores_checkin'
var26 = 'review_scores_communication'
var27 = 'review_scores_value'
var28 = 'guests_included'
var29 = 'security_deposit'
var30 = 'host_since'
var31 = 'longitude_x'
var32 = 'latitude_x'
var33 = 'amenities'

# big_data = test_data[big_data.price_x < 500]

data = test_data[[var, var2, var3, var4, var5, var6, var8, var11, var12, var13, var14, var15, var16, var17, var18, var19, var20, var21, var22, var23, var24,
                 var25, var26, var27, var28, var29, var30, var31, var32, var33]]


data[var17] = data[var17].replace('Shared room', 5)
data[var] = data[var].replace('2018-10-31', 0)
data[var2] = data[var2].replace('2018-07-20', 0)
data[var6] = data[var6].replace('moderate', 15)
data[var18] = data[var6].replace('Real Bed', 1)
data[var21] = data[var21].str.replace(',', '')
data[var21] = data[var21].str.replace('$', '')
data[var29] = data[var29].str.replace(',', '')
data[var29] = data[var29].str.replace('$', '')
data[var21] = data[var21].replace('f', 0)
data[var26] = data[var26].replace('2018-10-31', 5)
data[var28] = data[var28].replace('f', 0)



test_data[var17] = test_data[var17].replace('Shared room', 5)
test_data[var] = test_data[var].replace('2018-10-31', 0)
test_data[var2] = test_data[var2].replace('2018-07-20', 0)
test_data[var6] = test_data[var6].replace('moderate', 15)
test_data[var18] = test_data[var6].replace('Real Bed', 1)
test_data[var29] = test_data[var29].str.replace(',', '')
test_data[var29] = test_data[var29].str.replace('$', '')
test_data[var21] = test_data[var21].str.replace(',', '')
test_data[var21] = test_data[var21].str.replace('$', '')
test_data[var21] = test_data[var21].replace('f', 0)
test_data[var26] = test_data[var26].replace('2018-10-31', 5)
test_data[var28] = test_data[var28].replace('f', 0)

data[var30] = (test_data.host_since - test_data.host_since.min())
data[var30] = data[var30].values.astype('timedelta64[D]').astype('float')

test_data[var30] = (test_data.host_since - test_data.host_since.min())
test_data[var30] = test_data[var30].values.astype('timedelta64[D]').astype('float')


data[var][4476] = 0
data[var2][3105] = 0
data[var2][4476] = 0
data[var3][3105] = 0
data[var3][4476] = 0


data[var] = data[var].fillna(data[var].median())
data[var2] = data[var2].fillna(data[var2].median())
data[var3] = data[var3].fillna(data[var3].median())
data[var4] = data[var4].fillna(data[var4].median())
data[var5] = data[var5].fillna(data[var5].median())

data[var6][17990] = data[var6].median()
data[var6][6215] = data[var6].median()
data[var6][11299] = data[var6].median()
data[var6][12737] = data[var6].median()
data[var6][14598] = data[var6].median()
# data[var7][872] = 8000
# data[var7][2372] = 8000
# data[var7][4391] = 8000
# data[var7][17952] = 8000
# data[var7][17990] = data[var7].median()
# data[var7][6351] = data[var7].median()
# data[var7][8341] = data[var7].median()


data[var6] = data[var6].fillna(data[var6].median())
# data[var7] = data[var7].fillna(data[var7].median())
data[var8] = data[var8].fillna(data[var8].median())
# data[var10] = data[var10].fillna(data[var10].median())
data[var11] = data[var11].fillna(data[var11].median())
data[var12] = data[var12].fillna(data[var12].median())
data[var13] = data[var13].fillna(data[var13].median())
data[var14] = data[var14].fillna(data[var14].median())
data[var15] = data[var15].fillna(data[var15].median())
data[var16] = data[var16].fillna(data[var16].median())
data[var17] = data[var17].fillna(data[var17].median())
data[var18] = data[var18].fillna(data[var18].median())
data[var19] = data[var19].fillna(data[var19].median())
data[var20] = data[var20].fillna(data[var20].median())
data[var21] = data[var21].fillna(data[var21].median())
data[var22] = data[var22].fillna('Apartment')
data[var23] = data[var23].fillna(data[var23].median())
data[var24] = data[var24].fillna(data[var24].median())
data[var25] = data[var25].fillna(data[var25].median())
data[var26] = data[var26].fillna(data[var26].median())
data[var27] = data[var27].fillna(data[var27].median())
data[var28] = data[var28].fillna(data[var28].median())
data[var29] = data[var29].fillna(data[var29].median())
data[var30] = data[var30].fillna(data[var30].median())
data[var31] = data[var31].fillna(data[var31].median())
data[var32] = data[var32].fillna(data[var32].median())






# data[var6][17990] = data[var6].median()

# data = data.drop(data.index[17990])
# data = data.drop(data.index[14598])

data = data[[var31, var32]]

X = data.iloc[:, :].values
# y = data.iloc[:, -1].values

# plt.scatter(data[var6].values, data[var7].values, s=100, c='red', alpha=0.5)
# plt.show()

print(X)
# X[:,-8:] = sc.fit_transform(X[:,-8:])
# X = sc.fit_transform(X)
# print(X[0])
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

# data.head()


# data = data[[var31, var32]]
# X = data.iloc[:, :-1].values
# X = ct.fit_transform(X)
# X = X.todense()
# X = np.array(X)
y_pred = classifier.predict(X)

data['loc_class'] = y_pred
test_data['loc_class'] = y_pred

big_data.to_csv('airbnb_coded.2.0.csv')
test_data.to_csv('airbnb_test_coded.csv')
print("done")

[[13.43573367 52.47111954]
 [13.36623169 52.50338753]
 [13.30064836 52.50791325]
 ...
 [13.45286474 52.51908785]
 [13.40887987 52.53712419]
 [13.41186395 52.49068768]]
done


In [7]:
#Training
import pandas as pd
import seaborn as sns
import sklearn.cluster as cluster
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler as sc
from sklearn.neighbors import KNeighborsRegressor as KNN

big_data = pd.read_csv('airbnb_coded.2.0.csv')
sc = sc()
pd.options.mode.chained_assignment = None  # default='warn'



from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
var = 'bathrooms'
var2 = 'accommodates'
var3 = 'cleaning_fee'
var4 = 'bedrooms'
var5 = 'beds'
var6 = 'minimum_nights_x'
var7 = 'maximum_nights'
var8 = 'number_of_reviews_y'
var9 = 'listing_class'
var10 = 'price_x'
var11 = 'bed_code'
var12 = 'cancellation_policy_mapped'
var13 = 'room_code'
var14 = 'superhost'
var15 = 'instant_book'
var16 = 'review_scores_location'
var17 = 'review_scores_rating'
var18 = 'host_total_listings_count'
var19 = 'availability_90'
var20 = 'room_code'
var21 = 'extra_people'
var22 = 'property_type'
var23 = 'review_scores_value'
var24 = 'review_scores_cleanliness'
var25 = 'review_scores_checkin'
var26 = 'review_scores_communication'
var27 = 'review_scores_value'
var28 = 'guests_included'
var29 = 'security_deposit'
var30 = 'host_since'
var31 = 'loc_class'
var32 = 'profile_pic'
var33 = 'amenities'

big_data = big_data[big_data.price_x < 400]
big_data = big_data[big_data.price_x > 8]

data = big_data[[var, var2, var3, var4, var5, var6, var7, var8, var11, var12, var13, var14, var15, var16, var17, var18, var19, var21, var22, var23, var24,
                 var25, var26, var27, var28, var29, var30, var31, var32, var33, var9, var10]]

data[var] = data[var].fillna(data[var].median())
data[var2] = data[var2].fillna(data[var2].median())
data[var3] = data[var3].fillna(data[var3].median())
data[var4] = data[var4].fillna(data[var4].median())
data[var5] = data[var5].fillna(data[var5].median())

data[var6][17990] = data[var6].median()
data[var6][6215] = data[var6].median()
data[var6][11299] = data[var6].median()
data[var6][12737] = data[var6].median()
data[var6][14598] = data[var6].median()
# data[var7][872] = 8000
# data[var7][2372] = 8000
# data[var7][4391] = 8000
# data[var7][17952] = 8000
# data[var7][17990] = data[var7].median()
# data[var7][6351] = data[var7].median()
# data[var7][8341] = data[var7].median()


data[var6] = data[var6].fillna(data[var6].median())
data[var7] = data[var7].fillna(data[var7].median())
data[var8] = data[var8].fillna(data[var8].median())
data[var10] = data[var10].fillna(data[var10].median())
data[var11] = data[var11].fillna(data[var11].median())
data[var12] = data[var12].fillna(data[var12].median())
data[var13] = data[var13].fillna(data[var13].median())
data[var14] = data[var14].fillna(data[var14].median())
data[var15] = data[var15].fillna(data[var15].median())
data[var16] = data[var16].fillna(data[var16].median())
data[var17] = data[var17].fillna(data[var17].median())
data[var18] = data[var18].fillna(data[var18].median())
data[var19] = data[var19].fillna(data[var19].median())
data[var20] = data[var20].fillna(data[var20].median())
data[var21] = data[var21].fillna(data[var21].median())
data[var22] = data[var22].fillna('Apartment')
data[var23] = data[var23].fillna(data[var23].median())
data[var24] = data[var24].fillna(data[var24].median())
data[var25] = data[var25].fillna(data[var25].median())
data[var26] = data[var26].fillna(data[var26].median())
data[var27] = data[var27].fillna(data[var27].median())
data[var28] = data[var28].fillna(data[var28].median())
data[var29] = data[var29].fillna(data[var29].median())
data[var30] = data[var30].fillna(data[var30].median())
data[var31] = data[var31].fillna(data[var31].median())
data[var32] = data[var32].fillna(data[var32].median())





# data[var6][17990] = data[var6].median()

# data = data.drop(data.index[17990])
data = data.drop(data.index[14598])

data = data[[var2, var3, var6, var18, var19, var21, var8, var16, var17, var, var29,
             var9, var13, var12, var31, var10]]
# data = data[[var, var2, var3, var6, var8, var18, var17, var21, var19, var9, var12, var20, var22, var10]]


X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
X = ct.fit_transform(X)
# X = X.todense()
X = np.array(X)
X = ct.fit_transform(X)
# X = X.todense()
X = np.array(X)
X = ct.fit_transform(X)
# X = X.todense()
X = np.array(X)
X = ct.fit_transform(X)
# X = X.todense()
X = np.array(X)
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)

# from sklearn.feature_extraction.text import CountVectorizer
# vect = CountVectorizer()
# amenities = data[var33].values
# # print(amenities)
# # for i in range(len(amenities)):
# # print(amenities)
# vect.fit(amenities)
# amenities_array = vect.transform(amenities)
# amenities_array = amenities_array.todense()

# X = np.concatenate((X, amenities_array),axis=1)
# plt.scatter(data[var6].values, data[var7].values, s=100, c='red', alpha=0.5)
# plt.show()

print(len(X[0]))
print(X)
# X[:,-8:] = sc.fit_transform(X[:,-8:])
# X = sc.fit_transform(X)
# print(X[0])
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

# data.head()

import keras
from keras.models import Sequential
from keras.layers import Dense

ann = Sequential()
ann.add(Dense(output_dim=17, init='uniform', activation='relu', input_dim=26))
ann.add(Dense(output_dim=17, init='uniform', activation='relu'))
ann.add(Dense(output_dim=17, init='uniform', activation='relu'))
ann.add(Dense(output_dim=17, init='uniform', activation='relu'))
ann.add(Dense(output_dim=17, init='uniform', activation='relu'))
ann.add(Dense(output_dim=1, init='uniform'))
ann.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_squared_error'])
ann.fit(X, y, batch_size=12, nb_epoch=100)
# from xgboost import XGBRegressor
# xgb = XGBRegressor(n_estimators=1000,learning_rate=0.01,max_depth=9,subsample=0.8)
# xgb.fit(X, y)
# print("done")

26
[[  1.   0.   0. ...  97.   1. 100.]
 [  1.   0.   0. ...  75.   1. 100.]
 [  1.   0.   0. ...  80.   1.   0.]
 ...
 [  1.   0.   0. ...  99.   1.   0.]
 [  1.   0.   0. ...  90.   1.   0.]
 [  1.   0.   0. ... 100.   1. 100.]]


Using TensorFlow backend.
<ipython-input-7-fab96fddf885>:174: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=26, units=17, kernel_initializer="uniform")`
  ann.add(Dense(output_dim=17, init='uniform', activation='relu', input_dim=26))
<ipython-input-7-fab96fddf885>:175: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=17, kernel_initializer="uniform")`
  ann.add(Dense(output_dim=17, init='uniform', activation='relu'))
<ipython-input-7-fab96fddf885>:176: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=17, kernel_initializer="uniform")`
  ann.add(Dense(output_dim=17, init='uniform', activation='relu'))
<ipython-input-7-fab96fddf885>:177: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=17, kernel_initializer="uniform")`
  ann.add(Dense(output_dim=17, init='uniform', activation='relu'))
<ipython-input-7-fab96fddf885>:178

Epoch 1/100
17930/17930 [==============================] - 2s 90us/step - loss: 1527.0010 - mean_squared_error: 1527.0024
Epoch 2/100
17930/17930 [==============================] - 1s 83us/step - loss: 1121.0281 - mean_squared_error: 1121.0278
Epoch 3/100
17930/17930 [==============================] - 1s 79us/step - loss: 961.0929 - mean_squared_error: 961.0925
Epoch 4/100
17930/17930 [==============================] - 1s 80us/step - loss: 925.9189 - mean_squared_error: 925.9184
Epoch 5/100
17930/17930 [==============================] - 1s 82us/step - loss: 910.7356 - mean_squared_error: 910.7359
Epoch 6/100
17930/17930 [==============================] - 2s 84us/step - loss: 892.3663 - mean_squared_error: 892.3672
Epoch 7/100
17930/17930 [==============================] - 1s 80us/step - loss: 881.5518 - mean_squared_error: 881.5519
Epoch 8/100
17930/17930 [==============================] - 1s 79us/step - loss: 868.0173 - mean_squared_error: 868.0181
Epoch 9/100
17930/17930 [===========

In [8]:
#Test
import pandas as pd
import seaborn as sns
import sklearn.cluster as cluster
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler as sc
from sklearn.neighbors import KNeighborsRegressor as KNN

test_data = pd.read_csv('airbnb_test_coded.csv')
sc = sc()
pd.options.mode.chained_assignment = None  # default='warn'


from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
var = 'bathrooms'
var2 = 'accommodates'
var3 = 'cleaning_fee'
var4 = 'bedrooms'
var5 = 'beds'
var6 = 'minimum_nights_x'
var7 = 'maximum_nights'
var8 = 'number_of_reviews_y'
var9 = 'listing_class'
var10 = 'price_x'
var11 = 'bed_code'
var12 = 'cancellation_policy_mapped'
var13 = 'room_code'
var14 = 'superhost'
var15 = 'instant_book'
var16 = 'review_scores_location'
var17 = 'review_scores_rating'
var18 = 'host_total_listings_count'
var19 = 'availability_90'
var20 = 'room_code'
var21 = 'extra_people'
var22 = 'property_type'
var23 = 'review_scores_value'
var24 = 'review_scores_cleanliness'
var25 = 'review_scores_checkin'
var26 = 'review_scores_communication'
var27 = 'review_scores_value'
var28 = 'guests_included'
var29 = 'security_deposit'
var30 = 'host_since'
var31 = 'loc_class'
var32 = 'profile_pic'
var33 = 'amenities'

# big_data = big_data[big_data.price_x < 500]

data = test_data[[var, var2, var3, var4, var5, var6, var8, var11, var12, var13, var14, var15, var16, var17, var18, var19, var21, var22, var23, var24,
                 var25, var26, var27, var28, var29, var30, var31, var32, var33, var9]]

data[var] = data[var].fillna(data[var].median())
data[var2] = data[var2].fillna(data[var2].median())
data[var3] = data[var3].fillna(data[var3].median())
data[var4] = data[var4].fillna(data[var4].median())
data[var5] = data[var5].fillna(data[var5].median())

data[var6][17990] = data[var6].median()
data[var6][6215] = data[var6].median()
data[var6][11299] = data[var6].median()
data[var6][12737] = data[var6].median()
data[var6][14598] = data[var6].median()
# data[var7][872] = 8000
# data[var7][2372] = 8000
# data[var7][4391] = 8000
# data[var7][17952] = 8000
# data[var7][17990] = data[var7].median()
# data[var7][6351] = data[var7].median()
# data[var7][8341] = data[var7].median()


data[var6] = data[var6].fillna(data[var6].median())
# data[var7] = data[var7].fillna(data[var7].median())
data[var8] = data[var8].fillna(data[var8].median())
# data[var10] = data[var10].fillna(data[var10].median())
data[var11] = data[var11].fillna(data[var11].median())
data[var12] = data[var12].fillna(data[var12].median())
data[var13] = data[var13].fillna(data[var13].median())
data[var14] = data[var14].fillna(data[var14].median())
data[var15] = data[var15].fillna(data[var15].median())
data[var16] = data[var16].fillna(data[var16].median())
data[var17] = data[var17].fillna(data[var17].median())
data[var18] = data[var18].fillna(data[var18].median())
data[var19] = data[var19].fillna(data[var19].median())
data[var20] = data[var20].fillna(data[var20].median())
data[var21] = data[var21].fillna(data[var21].median())
data[var22] = data[var22].fillna('Apartment')
data[var23] = data[var23].fillna(data[var23].median())
data[var24] = data[var24].fillna(data[var24].median())
data[var25] = data[var25].fillna(data[var25].median())
data[var26] = data[var26].fillna(data[var26].median())
data[var27] = data[var27].fillna(data[var27].median())
data[var28] = data[var28].fillna(data[var28].median())
data[var29] = data[var29].fillna(data[var29].median())
data[var30] = data[var30].fillna(data[var30].median())
data[var31] = data[var31].fillna(data[var31].median())
data[var32] = data[var32].fillna(data[var32].median())





# data[var6][17990] = data[var6].median()

# data = data.drop(data.index[17990])

data = data[[var2, var3, var6, var18, var19, var21, var8, var16, var17, var, var29,
             var9, var13, var12, var31]]
# data = data[[var, var2, var3, var6, var8, var18, var17, var21, var19, var9, var12, var20, var22, var10]]


X = data.iloc[:, :].values
# y = data.iloc[:, -1].values
X = ct.fit_transform(X)
# X = X.todense()
X = np.array(X)
X = ct.fit_transform(X)
# X = X.todense()
X = np.array(X)
X = ct.fit_transform(X)
# X = X.todense()
X = np.array(X)
X = ct.fit_transform(X)
# X = X.todense()
X = np.array(X)
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)

# from sklearn.feature_extraction.text import CountVectorizer
# vect = CountVectorizer()
# amenities = data[var33].values
# # print(amenities)
# # for i in range(len(amenities)):
# # print(amenities)
# vect.fit(amenities)
# amenities_array = vect.transform(amenities)
# amenities_array = amenities_array.todense()

# X = np.concatenate((X, amenities_array),axis=1)
# plt.scatter(data[var6].values, data[var7].values, s=100, c='red', alpha=0.5)
# plt.show()

print(len(X[0]))
print(X)
# X[:,-8:] = sc.fit_transform(X[:,-8:])
# X = sc.fit_transform(X)
# print(X[0])
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

# data.head()

print(len(X[0]))
print(X)
# X[:,-8:] = sc.fit_transform(X[:,-8:])
# X = sc.fit_transform(X)
# print(X[0])
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

# data.head()


y_pred = ann.predict(X)
print("done")

26
[[  1.    0.    0.  ...  98.    1.  200. ]
 [  1.    0.    0.  ...  80.    1.  100. ]
 [  1.    0.    0.  ...  90.    1.5   0. ]
 ...
 [  0.    1.    0.  ... 100.    1.  350. ]
 [  1.    0.    0.  ... 100.    1.  100. ]
 [  1.    0.    0.  ... 100.    1.  200. ]]
26
[[  1.    0.    0.  ...  98.    1.  200. ]
 [  1.    0.    0.  ...  80.    1.  100. ]
 [  1.    0.    0.  ...  90.    1.5   0. ]
 ...
 [  0.    1.    0.  ... 100.    1.  350. ]
 [  1.    0.    0.  ... 100.    1.  100. ]
 [  1.    0.    0.  ... 100.    1.  200. ]]
done


In [9]:
y_pred

array([[47.375336],
       [59.248165],
       [30.338474],
       ...,
       [90.12008 ],
       [66.00599 ],
       [50.426754]], dtype=float32)

In [12]:
print(test_data['index'])

0          0
1          1
2          2
3          3
4          4
        ... 
4506    4506
4507    4507
4508    4508
4509    4509
4510    4510
Name: index, Length: 4511, dtype: int64


In [13]:
save_data = test_data[['index', 'id']]
save_data['Predicted values'] = y_pred
save_data.to_csv('predicted.csv')