In [323]:
import pandas as pd
import seaborn as sns
import sklearn.cluster as cluster
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler as sc
from sklearn.neighbors import KNeighborsRegressor as KNN

big_data = pd.read_csv('airbnb_coded.2.0.csv')
sc = sc()
pd.options.mode.chained_assignment = None  # default='warn'

In [385]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
var = 'bathrooms'
var2 = 'accommodates'
var3 = 'cleaning_fee'
var4 = 'bedrooms'
var5 = 'beds'
var6 = 'minimum_nights_x'
var7 = 'maximum_nights'
var8 = 'number_of_reviews_y'
var9 = 'listing_class'
var10 = 'price_x'
var11 = 'bed_code'
var12 = 'cancellation_policy_mapped'
var13 = 'room_code'
var14 = 'superhost'
var15 = 'instant_book'
var16 = 'review_scores_location'
var17 = 'review_scores_rating'
var18 = 'host_total_listings_count'
var19 = 'availability_90'
var20 = 'room_code'
var21 = 'extra_people'
var22 = 'property_type'
var23 = 'review_scores_value'
var24 = 'review_scores_cleanliness'
var25 = 'review_scores_checkin'
var26 = 'review_scores_communication'
var27 = 'review_scores_value'
var28 = 'guests_included'
var29 = 'security_deposit'
var30 = 'host_since'
var31 = 'loc_class'
var32 = 'profile_pic'
var33 = 'amenities'

# big_data = big_data[big_data.price_x < 500]
# big_data = big_data[big_data.price_x > 5]

data = big_data[[var, var2, var3, var4, var5, var6, var7, var8, var11, var12, var13, var14, var15, var16, var17, var18, var19, var21, var22, var23, var24,
                 var25, var26, var27, var28, var29, var30, var31, var32, var33, var9, var10]]

data[var] = data[var].fillna(data[var].median())
data[var2] = data[var2].fillna(data[var2].median())
data[var3] = data[var3].fillna(data[var3].median())
data[var4] = data[var4].fillna(data[var4].median())
data[var5] = data[var5].fillna(data[var5].median())

data[var6][17990] = data[var6].median()
data[var6][6215] = data[var6].median()
data[var6][11299] = data[var6].median()
data[var6][12737] = data[var6].median()
data[var6][14598] = data[var6].median()
# data[var7][872] = 8000
# data[var7][2372] = 8000
# data[var7][4391] = 8000
# data[var7][17952] = 8000
# data[var7][17990] = data[var7].median()
# data[var7][6351] = data[var7].median()
# data[var7][8341] = data[var7].median()


data[var6] = data[var6].fillna(data[var6].median())
data[var7] = data[var7].fillna(data[var7].median())
data[var8] = data[var8].fillna(data[var8].median())
data[var10] = data[var10].fillna(data[var10].median())
data[var11] = data[var11].fillna(data[var11].median())
data[var12] = data[var12].fillna(data[var12].median())
data[var13] = data[var13].fillna(data[var13].median())
data[var14] = data[var14].fillna(data[var14].median())
data[var15] = data[var15].fillna(data[var15].median())
data[var16] = data[var16].fillna(data[var16].median())
data[var17] = data[var17].fillna(data[var17].median())
data[var18] = data[var18].fillna(data[var18].median())
data[var19] = data[var19].fillna(data[var19].median())
data[var20] = data[var20].fillna(data[var20].median())
data[var21] = data[var21].fillna(data[var21].median())
data[var22] = data[var22].fillna('Apartment')
data[var23] = data[var23].fillna(data[var23].median())
data[var24] = data[var24].fillna(data[var24].median())
data[var25] = data[var25].fillna(data[var25].median())
data[var26] = data[var26].fillna(data[var26].median())
data[var27] = data[var27].fillna(data[var27].median())
data[var28] = data[var28].fillna(data[var28].median())
data[var29] = data[var29].fillna(data[var29].median())
data[var30] = data[var30].fillna(data[var30].median())
data[var31] = data[var31].fillna(data[var31].median())
data[var32] = data[var32].fillna(data[var32].median())





# data[var6][17990] = data[var6].median()

# data = data.drop(data.index[17990])
data = data.drop(data.index[14598])

data = data[[var2, var3, var6, var18, var19, var21, var8, var16, var17, var, var29,
             var9, var13, var12, var31, var10]]
# data = data[[var, var2, var3, var6, var8, var18, var17, var21, var19, var9, var12, var20, var22, var10]]


X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
X = ct.fit_transform(X)
# X = X.todense()
X = np.array(X)
X = ct.fit_transform(X)
# X = X.todense()
X = np.array(X)
X = ct.fit_transform(X)
# X = X.todense()
X = np.array(X)
X = ct.fit_transform(X)
# X = X.todense()
X = np.array(X)
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)
# X = ct.fit_transform(X)
# # X = X.todense()
# X = np.array(X)

# from sklearn.feature_extraction.text import CountVectorizer
# vect = CountVectorizer()
# amenities = data[var33].values
# # print(amenities)
# # for i in range(len(amenities)):
# # print(amenities)
# vect.fit(amenities)
# amenities_array = vect.transform(amenities)
# amenities_array = amenities_array.todense()

# X = np.concatenate((X, amenities_array),axis=1)
# plt.scatter(data[var6].values, data[var7].values, s=100, c='red', alpha=0.5)
# plt.show()

print(len(X[0]))
print(X)
# X[:,-8:] = sc.fit_transform(X[:,-8:])
# X = sc.fit_transform(X)
# print(X[0])
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

# data.head()

[[  1.   0.   0. ...  97.   0.   0.]
 [  1.   0.   0. ...  75.   0.   0.]
 [  0.   0.   0. ...  80.  10.  83.]
 ...
 [  0.   0.   0. ...  99.  19.   6.]
 [  0.   0.   0. ...  90.  10.   0.]
 [  1.   0.   0. ... 100.   0.   0.]]


In [386]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=0)

In [387]:
from xgboost import XGBRegressor

In [388]:
xgb = XGBRegressor()

In [389]:
xgb.fit(X_train, y_train)
xgb.score(X_train, y_train)

0.8327878555747149

In [390]:
xgb.score(X_test, y_test)

0.1484313243469848

In [391]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(xgb, X, 
                          y, scoring='r2', cv=10)
print(scores)
print(np.mean(scores))
np.std(scores)

[ 0.39529418 -0.96103356  0.15659256  0.42446651  0.46812067  0.03365646
  0.0128774  -0.02217939  0.06341101  0.31929879]
0.08905046120645795


0.3914251311020669